app_euphoria/apl_euphoria/urls.py
from django.urls import path
from apl_euphoria.views import index, gestion
from apl_euphoria.Views.cliente.views import ClienteListView, ClienteCreateView, ClienteUpdateView, ClienteDeleteView
from apl_euphoria.Views.productos.views import ProductoListView, ProductoCreateView, ProductoUpdateView, ProductoDeleteView
from apl_euphoria.Views.pedidos.views import PedidoListView, PedidoCreateView, PedidoUpdateView, PedidoDeleteView
from apl_euphoria.Views.detalles_pedidos.views import Detalle_PedidoListView, Detalle_PedidoCreateView, Detalle_PedidoUpdateView, Detalle_PedidoDeleteView
# from apl_euphoria.Views.pagos.views import PagoListView, PagoCreateView, PagoUpdateView, PagoDeleteView
# from apl_euphoria.Views.proveedores.views import ProveedorListView, ProveedorCreateView, ProveedorUpdateView, ProveedorDeleteView
from apl_euphoria.Views.compras.views import CompraListView, CompraCreateView, CompraUpdateView, CompraDeleteView
# from apl_euphoria.Views.facturas.views import FacturaListView, FacturaCreateView, FacturaUpdateView, FacturaDeleteView
# from apl_euphoria.Views.promociones.views import PromocionListView, PromocionCreateView, PromocionUpdateView, PromocionDeleteView
from apl_euphoria.Views.categoria_producto.views import CategoriaProductoListView, CategoriaProductoCreateView, CategoriaProductoUpdateView, CategoriaProductoDeleteView
from apl_euphoria.Views.marca_producto.views import MarcaCosmeticoListView, MarcaCosmeticoCreateView, MarcaCosmeticoUpdateView, MarcaCosmeticoDeleteView
from apl_euphoria.Views.pqr.views import PqrListView, PqrCreateView, PqrUpdateView, PqrDeleteView
from apl_euphoria.Views.administrador.views import AdministradorListView, AdministradorCreateView, AdministradorUpdateView, AdministradorDeleteView
# from apl_euphoria.Views.vendedor.views import VendedorListView, VendedorCreateView, VendedorUpdateView, VendedorDeleteView
from apl_euphoria.Views.ventas.views import VentaListView, VentaCreateView, VentaUpdateView, VentaDeleteView
app_name = 'apl_euphoria'

urlpatterns = [
    #  Administrador URLs
    path('administradores/', AdministradorListView.as_view(), name='lista_administrador'),
    path('administradores/crear/', AdministradorCreateView.as_view(), name='administrador_crear'),
    path('administradores/<int:pk>/editar/', AdministradorUpdateView.as_view(), name='administrador_editar'),
    path('administradores/<int:pk>/eliminar/', AdministradorDeleteView.as_view(), name='administrador_eliminar'),
    
    # # Vendedor URLs
    # path('vendedores/', VendedorListView.as_view(), name='vendedor_lista'),
    # path('vendedores/crear/', VendedorCreateView.as_view(), name='vendedor_crear'),
    # path('vendedores/<int:pk>/editar/', VendedorUpdateView.as_view(), name='vendedor_editar'),
    # path('vendedores/<int:pk>/eliminar/', VendedorDeleteView.as_view(), name='vendedor_eliminar'),
    
    # Venta URLs
     path('ventas/', VentaListView.as_view(), name='venta_lista'),
     path('ventas/crear/', VentaCreateView.as_view(), name='venta_crear'),
     path('ventas/<int:pk>/editar/', VentaUpdateView.as_view(), name='venta_editar'),
     path('ventas/<int:pk>/eliminar/', VentaDeleteView.as_view(), name='venta_eliminar'),
    
    # Cliente URLs
    path('clientes/', ClienteListView.as_view(), name='cliente_lista'),  
    path('clientes/crear/', ClienteCreateView.as_view(), name='cliente_crear'),  
    path('clientes/<int:pk>/editar/', ClienteUpdateView.as_view(), name='cliente_actualizar'),  
    path('clientes/<int:pk>/eliminar/', ClienteDeleteView.as_view(), name='cliente_eliminar'),  

    # Producto URLs
    path('productos/', ProductoListView.as_view(), name='producto_lista'), 
    path('productos/crear/', ProductoCreateView.as_view(), name='producto_crear'), 
    path('productos/<int:pk>/editar/', ProductoUpdateView.as_view(), name='producto_editar'),  
    path('productos/<int:pk>/eliminar/', ProductoDeleteView.as_view(), name='producto_eliminar'), 
    

    # # Pedido URLs
     path('pedidos/', PedidoListView.as_view(), name='pedido_lista'),  
     path('pedidos/crear/', PedidoCreateView.as_view(), name='pedido_crear'),  
     path('pedidos/<int:pk>/editar/', PedidoUpdateView.as_view(), name='pedido_editar'),  
     path('pedidos/<int:pk>/eliminar/', PedidoDeleteView.as_view(), name='pedido_eliminar'),  

    # # Detalle Pedido URLs
     path('detalles-pedido/', Detalle_PedidoListView.as_view(), name='detalle_pedido_lista'), 
     path('detalles-pedido/crear/', Detalle_PedidoCreateView.as_view(), name='detalle_pedido_crear'),  
     path('detalles-pedido/<int:pk>/editar/', Detalle_PedidoUpdateView.as_view(), name='detalle_pedido_editar'),  
     path('detalles-pedido/<int:pk>/eliminar/', Detalle_PedidoDeleteView.as_view(), name='detalle_pedido_eliminar'),  

    # # Pago URLs
    # path('pagos/', PagoListView.as_view(), name='pago_lista'),  
    # path('pagos/crear/', PagoCreateView.as_view(), name='pago_crear'),  
    # path('pagos/<int:pk>/editar/', PagoUpdateView.as_view(), name='pago_editar'),  
    # path('pagos/<int:pk>/eliminar/', PagoDeleteView.as_view(), name='pago_eliminar'),  

    # # Proveedor URLs
    # path('proveedores/', ProveedorListView.as_view(), name='proveedor_lista'),  
    # path('proveedores/crear/', ProveedorCreateView.as_view(), name='proveedor_crear'),  
    # path('proveedores/<int:pk>/editar/', ProveedorUpdateView.as_view(), name='proveedor_editar'),  
    # path('proveedores/<int:pk>/eliminar/', ProveedorDeleteView.as_view(), name='proveedor_eliminar'),  

    # # Compra URLs
    path('compras/', CompraListView.as_view(), name='compra_lista'),
    path('compras/crear/', CompraCreateView.as_view(), name='compra_crear'),
    path('compras/editar/<int:pk>/', CompraUpdateView.as_view(), name='compra_editar'),
    path('compras/eliminar/<int:pk>/', CompraDeleteView.as_view(), name='compra_eliminar'), 

    # # Factura URLs
    # path('facturas/', FacturaListView.as_view(), name='factura_lista'),  
    # path('facturas/crear/', FacturaCreateView.as_view(), name='factura_crear'),  
    # path('facturas/<int:pk>/editar/', FacturaUpdateView.as_view(), name='factura_editar'),  
    # path('facturas/<int:pk>/eliminar/', FacturaDeleteView.as_view(), name='factura_eliminar'),  

    # # Promocion URLs
    # path('promociones/', PromocionListView.as_view(), name='promocion_lista'),  
    # path('promociones/crear/', PromocionCreateView.as_view(), name='promocion_crear'),  
    # path('promociones/<int:pk>/editar/', PromocionUpdateView.as_view(), name='promocion_editar'), 
    # path('promociones/<int:pk>/eliminar/', PromocionDeleteView.as_view(), name='promocion_eliminar'),  

    # Categoria Producto URLs
    path('categorias/', CategoriaProductoListView.as_view(), name='categoria_lista'),  
    path('categorias/crear/', CategoriaProductoCreateView.as_view(), name='categoria_crear'),  
    path('categorias/<int:pk>/editar/', CategoriaProductoUpdateView.as_view(), name='categoria_editar'),  
    path('categorias/<int:pk>/eliminar/', CategoriaProductoDeleteView.as_view(), name='categoria_eliminar'),  

    #  Marca Cosmetico URLs
    path('marcas/', MarcaCosmeticoListView.as_view(), name='marca_lista'),  
    path('marcas/crear/', MarcaCosmeticoCreateView.as_view(), name='marca_crear'),  
    path('marcas/<int:pk>/editar/', MarcaCosmeticoUpdateView.as_view(), name='marca_editar'),  
    path('marcas/<int:pk>/eliminar/', MarcaCosmeticoDeleteView.as_view(), name='marca_eliminar'),  

    # PQR URLs
    path('pqrs/', PqrListView.as_view(), name='pqr_lista'),
    path('pqrs/crear/', PqrCreateView.as_view(), name='pqr_crear'),
    path('pqrs/<int:pk>/editar/', PqrUpdateView.as_view(), name='pqr_editar'),
    path('pqrs/<int:pk>/eliminar/', PqrDeleteView.as_view(), name='pqr_eliminar'),
  
















]

app_euphoria/app_euphoria/urls.py
from django.contrib import admin
from django.urls import path, include
from apl_euphoria.views import index, gestion
urlpatterns = [
    path('admin/', admin.site.urls),
        # Rutas generales (index y home)
    path('index/', index, ), 

    path('gestion/', include('apl_euphoria.urls')),  # Ruta base para todo lo de apl_euphoria
]

app_euphoria/apl_euphoria/models.py
from django.db import models

# Create your models here.

class Administrador(models.Model):
    id_administrador = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    correo = models.CharField(max_length=100)
    telefono = models.CharField(max_length=20)
    
    def __str__(self):
        return self.nombre

class Cliente(models.Model):
    id_cliente = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    correo = models.CharField(max_length=100)
    numero_telefono = models.CharField(max_length=20)
    Indexes = models.Index(fields=['id_cliente'])
    def __str__(self):
        return self.nombre

class Vendedor(models.Model):
    id_vendedor = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    telefono = models.CharField(max_length=20)
    correo = models.CharField(max_length=20)
    direccion = models.CharField(max_length=255)
    Indexes = models.Index(fields=['id_vendedor'])
    
class Venta(models.Model):
    id_venta = models.AutoField(primary_key=True)
    id_vendedor = models.ForeignKey('Vendedor', on_delete=models.CASCADE)
    detalles = models.TextField()
    total = models.DecimalField(max_digits=10, decimal_places=2)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2)
    fecha = models.DateField()
    cantidad = models.IntegerField()
    id_administrador = models.ForeignKey('Administrador', on_delete=models.CASCADE)
    id_pedido = models.ForeignKey('Pedido', on_delete=models.CASCADE)
    id_producto = models.ForeignKey('Producto', on_delete=models.CASCADE)

class Producto(models.Model):
    id_producto = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField()
    categoria = models.ForeignKey('CategoriaProducto', on_delete=models.CASCADE)
    marca = models.ForeignKey('MarcaCosmetico', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre

class Pedido(models.Model): 
    id_pedido = models.AutoField(primary_key=True)
    id_cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    fecha = models.DateTimeField()

class DetallePedido(models.Model):
    id_detalle = models.AutoField(primary_key=True)
    id_pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    id_producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)

class Pago(models.Model):
    id_pago = models.AutoField(primary_key=True)
    id_cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    metodo_pago = models.CharField(max_length=100)
    monto = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_pago = models.DateField()
    confirmacion_pago = models.TextField()

class Proveedor(models.Model):
    id_proveedor = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=255)
    telefono = models.CharField(max_length=20)
    correo = models.CharField(max_length=100)

class Compra(models.Model):
    id_compra = models.AutoField(primary_key=True)
    id_proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    id_producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    nombre_producto = models.CharField(max_length=100)
    cantidad = models.IntegerField()
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_compra = models.DateField()
    id_administrador = models.ForeignKey(Administrador, on_delete=models.CASCADE)

class Factura(models.Model):
    id_factura = models.AutoField(primary_key=True)
    id_pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    numero = models.CharField(max_length=100)
    fecha = models.DateField()
    total = models.DecimalField(max_digits=10, decimal_places=2)
    id_cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)

class Promocion(models.Model):
    id_promocion = models.AutoField(primary_key=True)
    descripcion = models.TextField()
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    descuento = models.DecimalField(max_digits=10, decimal_places=2)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    requisitos = models.CharField(max_length=100)
    rendimiento = models.CharField(max_length=100)

class CategoriaProducto(models.Model):
    id_categoria = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    
    def __str__(self):
        return self.nombre
    
class MarcaCosmetico(models.Model):
    id_marca = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    detalles = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    cantidades = models.IntegerField()
    
    def __str__(self):
        return self.nombre


class Pqr(models.Model):
    id_pqr = models.AutoField(primary_key=True)
    id_cliente = models.ForeignKey('Cliente', on_delete=models.CASCADE)
    direccion_cliente = models.CharField(max_length=255)
    telefono_cliente = models.CharField(max_length=20)
    descripcion = models.TextField()
    id_administrador = models.ForeignKey('Administrador', on_delete=models.CASCADE)
    

app_euphoria/apl_euphoria/Views/administrador/views.py
from django.shortcuts import render
from django.http import HttpResponse
from apl_euphoria.models import Administrador
from django.urls import reverse_lazy   
from django.views.generic import ListView, CreateView, UpdateView, DeleteView


class AdministradorListView(ListView):
    model = Administrador
    template_name = "Administrador/listar_administrador.html"
    context_object_name = 'administradores'   
    
    def get_queryset(self):
        return self.model.objects.all()
    
    
class AdministradorCreateView(CreateView):
    model = Administrador
    template_name = "Administrador/agregar.html"
    fields = '__all__'
        
    def get_success_url(self):
        return reverse_lazy('apl_euphoria:lista_administrador')
        

class AdministradorUpdateView(UpdateView):
    model = Administrador
    template_name = "Administrador/editar.html"
    fields = '__all__'
    
    def get_success_url(self):
        return reverse_lazy('apl_euphoria:lista_administrador')
class AdministradorDeleteView(DeleteView):
    model = Administrador
    template_name = "Administrador/eliminar.html"
    
    def get_success_url(self):
        return reverse_lazy('apl_euphoria:lista_administrador')
    

app_euphoria/apl_euphoria/Views/categoria_producto/views.py
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect,render
from django.views.generic import ListView
from apl_euphoria.models import CategoriaProducto
from django.http import JsonResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy


class CategoriaProductoListView(ListView):
    model = CategoriaProducto
    template_name = "Categoria_productos/lista_categoria.html"
    context_object_name = 'categoria_productos'   
    
    def get_queryset(self):
        return self.model.objects.all()
    
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
       print("Interceptando en dispatch")
       
       return super().dispatch(request, *args, **kwargs)
   
    def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context['titulo'] = 'Lista de Categorias'
       
       return context

class CategoriaProductoCreateView(CreateView):
    model = CategoriaProducto
    template_name = "Categoria_productos/crear.html"
    fields = '__all__'
    success_url = reverse_lazy('apl_euphoria:categoria_lista')

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
       print("Interceptando en dispatch")
       
       return super().dispatch(request, *args, **kwargs)
   
    def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context['titulo'] = 'Crear Categoria'
       
       return context
class CategoriaProductoUpdateView(UpdateView):
    model = CategoriaProducto
    template_name = "Categoria_productos/editar.html"
    fields = '__all__'
    success_url = reverse_lazy('apl_euphoria:categoria_lista')
    
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
       print("Interceptando en dispatch")
       
       return super().dispatch(request, *args, **kwargs)
   
    def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context['titulo'] = 'Editar Categoria'
       
       return context
class CategoriaProductoDeleteView(DeleteView):
    model = CategoriaProducto
    template_name = "Categoria_productos/eliminar.html"
    success_url = reverse_lazy('apl_euphoria:categoria_lista')
    
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
       print("Interceptando en dispatch")
       
       return super().dispatch(request, *args, **kwargs)
   
    def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context['titulo'] = 'Eliminar Categoria'
       
       return context

app_euphoria/apl_euphoria/templates/Compras/crear.html
{% extends "body.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="form-container">
  <h2><i class="fas fa-plus"></i> CREAR COMPRA</h2>
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Cerrar"></button>
      </div>
    {% endfor %}
  {% endif %}
  <form method="post" id="compraForm">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form %}
      <div class="mb-3">
        <label for="{{ field.id_for_label }}" class="form-label"><strong>{{ field.label }}</strong></label>
        {{ field|add_class:'form-control' }}
        {% if field.errors %}
          <div class="text-danger small">{{ field.errors }}</div>
        {% endif %}
      </div>
    {% endfor %}
  
    <div class="botones-container">
      <button type="submit" class="btn btn-primary btn-agregar"><i class="fas fa-save"></i> Guardar </button>
      <a href="{% url 'apl_euphoria:compra_lista' %}" class="btn btn-secondary"><i class="fas fa-times"></i> Cancelar</a>
    </div>
    
  </form>
</div>


{% endblock %}

}

app_euphoria/apl_euphoria/templates/Compras/editar.html
{% extends "body.html" %}

{% load widget_tweaks %}

{% block content %}
<div class="form-container">
  <h2><i class="fas fa-plus"></i> EDITAR COMPRA</h2>
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Cerrar"></button>
      </div>
    {% endfor %}
  {% endif %}
  <form method="post" id="compraForm">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form %}
      <div class="mb-3">
        <label for="{{ field.id_for_label }}" class="form-label"><strong>{{ field.label }}</strong></label>
        {{ field|add_class:'form-control' }}
        {% if field.errors %}
          <div class="text-danger small">{{ field.errors }}</div>
        {% endif %}
      </div>
    {% endfor %}
    <div class="botones-container">
      <button type="submit" class="btn btn-primary btn-agregar"><i class="fas fa-save"></i> Guardar </button>
      <a href="{% url 'apl_euphoria:compra_lista' %}" class="btn btn-secondary"><i class="fas fa-times"></i> Cancelar</a>
    </div>
  </form>
</div>
{% endblock %}




app_euphoria/apl_euphoria/templates/Compras/eliminar.html
{% extends "body.html" %}
{% block content %}

<div class="eliminar-container">
  <h1 class="titulo">🗑 ELIMINAR COMPRA</h1>

  <div class="eliminar-box">
    <h2 class="text-danger mb-4">¿Deseas eliminar esta compra?</h2>
    <p><strong>ID comprar:</strong> {{ object.id_compra }}</p>
    <p><strong>Nombre de la compra:</strong> {{ object.nombre }}</p>
    
    <form method="post" class="eliminar-form">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">
        <i class='far fa-trash-alt'></i> Sí, eliminar
      </button>
      <a href="{% url 'apl_euphoria:compra_lista' %}" class="btn btn-secondary">
        <i class='fas fa-times'></i> Cancelar
      </a>
    </form>
  </div>
</div>




<!-- Estilos CSS -->
 <style>
.eliminar-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  background-color: #f5f5f5;
  padding: 40px 20px;
  min-height: 100vh;
}

.titulo {
  margin-bottom: 20px;
  font-size: 2em;
  text-align: center;
}

.eliminar-box {
  background-color: #fff0ff;
  padding: 30px 40px;
  border-radius: 10px;
  box-shadow: 0 0 25px rgba(0,0,0,0.15);
  width: 100%;
  max-width: 520px;
  font-family: sans-serif;
}
</style>


{% endblock %}

app_euphoria/apl_euphoria/templates/Compras/listar_compras.html
{% extends 'body.html' %}

{% load static %}

{% block content %}
<div class="card">
  <div class="card-header d-flex justify-content-between align-items-center">
    <h3 class="card-title mb-0">Tabla de Compras</h3>
    <a href="{% url 'apl_euphoria:compra_crear' %}" class="btn btn-primary btn-sm">
      <i class="fas fa-plus me-1"></i> Agregar compra
    </a>
    
  </div>
  <div class="card-body">
    <table id="tabla-generica" class="table table-bordered table-striped dt-responsive nowrap" style="width:100%">
      <thead>
        <tr>
          <th>Id</th>
          <th>Nombre</th>
          <th>Proveedor</th>
          <th>Producto</th>
          <th>Cantidad</th>
          <th>Fecha</th>
          <th>Precio</th>
          <th>Administrador</th>
        </tr>
      </thead>
      <tbody>
        {% for compra in compra_list %}
        <tr>
          <td>{{compra.id_compra }}</td>
          <td>{{compra.nombre }}</td>
          <td>{{compra.proveedor }}</td>
          <td>{{compra.producto }}</td>
          <td>${{compra.precio|floatformat:2 }}</td>
          <td>{{compra.cantidad }}</td>
          <td>{{compra.fecha }}</td>
          <td>{{compra.administrador}}</td>
          <td class="text-center">
            <a href="{% url 'apl_euphoria:compra_editar' compra.id_compra %}" class="btn btn-info btn-sm" title="Editar">
              <i class='fas fa-edit'></i>
            </a>
            <a href="{% url 'apl_euphoria:compra_eliminar' compra.id_compra %}" class="btn btn-danger btn-sm" title="Eliminar">
              <i class='far fa-trash-alt'></i>
            </a> 
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  
{% endblock %}

{% block extra_scripts %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>
$(document).ready(function() {
    $('#tabla-generica').DataTable({
        responsive: true,
        autoWidth: false,
        language: {
            url: '//cdn.datatables.net/plug-ins/1.13.7/i18n/es-ES.json',
        },
    });
});
</script>
{% endblock %}